//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VotingSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Election
    {
        public System.Guid ID { get; set; }
        public System.Guid UserID { get; set; }
        public System.Guid CandidateID { get; set; }
    
        public virtual Candidate Candidate { get; set; }
        public virtual User User { get; set; }
    }
}
